# Pandas (2D DataFrame)


- A pandas DataFrame is a 2 dimentional data structure, like a 2 dimentional array, or a table with row and columns.

**create a DataFrame**

- list of list
- 2D array
- Dict
- this above are the options by using we can create the DataFrame

In [1]:
import pandas as pd
import numpy as np

In [7]:
# 1) using list of list 

d = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['a','b','c'])
d

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [9]:
# 2) using 2D Array

a = np.array([[11,12,13],[14,15,16],[17,18,19]])
d = pd.DataFrame(a)
d

    0   1   2
0  11  12  13
1  14  15  16
2  17  18  19

In [11]:
# 3) using Dict

d = {"name":['swaraj','ujjwal','abhishek','ram'],'mobile No':[9421403501,1965487345,1234567890,10987654321],'email':['swaraj@gmail.com','ujjwal@gmail.com','abhishek@gmail.com','ram@gmail.com']}
df = pd.DataFrame(d)
df

       name    mobile No               email
0    swaraj   9421403501    swaraj@gmail.com
1    ujjwal   1965487345    ujjwal@gmail.com
2  abhishek   1234567890  abhishek@gmail.com
3       ram  10987654321       ram@gmail.com

In [12]:
df.shape

(4, 3)

In [13]:
df.ndim

2

# Extraction

In [14]:
df = pd.DataFrame({"name":['swaraj','ujjwal','abhishek','ram'],
                  "age":[27,28,26,29],
                  "salary":[27000,27000,30000,10000]},
                 index=['a','b','c','d'])
df

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

In [31]:
# extract 26
# 1) by using index
print(df.iloc[2, 1])

print ("=====================")
# by using index name
print(df.loc['c','age'])

26
=====================
26

In [27]:
# extract last two row

# 1) by index 
print(df.iloc[2:,:])

print("=============================")
#2) by index name
print (df.loc['c':'d',:])

       name  age  salary
c  abhishek   26   30000
d       ram   29   10000
=============================
       name  age  salary
c  abhishek   26   30000
d       ram   29   10000

In [37]:
# extract 2nd column

# 1) by using index

print(df.iloc[:,1])

print("=========================")

# 2) by using column name

print(df['age'])

a    27
b    28
c    26
d    29
Name: age, dtype: int64
=========================
a    27
b    28
c    26
d    29
Name: age, dtype: int64

In [38]:
# extract name and salary

df[['name','salary']]

       name  salary
a    swaraj   27000
b    ujjwal   27000
c  abhishek   30000
d       ram   10000

**By using Condition**

In [33]:
print(df)

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

In [35]:
# 1) age grater than 26

df[df['age'] > 26]

     name  age  salary
a  swaraj   27   27000
b  ujjwal   28   27000
d     ram   29   10000

In [41]:
# 2) extract salary equeal to 27000 and more
df[df['salary'] >= 27000]

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000

In [42]:
# 3 ) salary is 30000 and age should be 26

df[(df['salary'] == 30000) & (df['age'] == 26)]

       name  age  salary
c  abhishek   26   30000

In [44]:
# age between 26 to 28

# 1) by using condition

print(df [(df['age'] >= 26) & (df['age'] <= 28) ])

print("=================================================")

# 2) by using between operator

print (df [df['age'].between(26,28)])

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
=================================================
       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000

In [49]:
# salary of 10000, 27000, 30000

df[df['salary'].isin([10000,27000,30000])]

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

# Modification

**1) Add**

In [2]:
df = pd.DataFrame({"name":['swaraj','ujjwal','abhishek','ram'],
                  "age":[27,28,26,29],
                  "salary":[27000,27000,30000,10000]},
                 index=['a','b','c','d'])
df

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

**Add single column**

In [3]:
df["Education"] = ['btech','btech','MCA','btech']
df

       name  age  salary Education
a    swaraj   27   27000     btech
b    ujjwal   28   27000     btech
c  abhishek   26   30000       MCA
d       ram   29   10000     btech

**Add single Row**

In [4]:
df.loc['e'] = ['rameshware',26,30000,'btech']

In [5]:
df

         name  age  salary Education
a      swaraj   27   27000     btech
b      ujjwal   28   27000     btech
c    abhishek   26   30000       MCA
d         ram   29   10000     btech
e  rameshware   26   30000     btech

**replace**

In [6]:
# replace rameshware age to 25

df.loc['e','age'] = 25
df

         name  age  salary Education
a      swaraj   27   27000     btech
b      ujjwal   28   27000     btech
c    abhishek   26   30000       MCA
d         ram   29   10000     btech
e  rameshware   25   30000     btech

In [7]:
df.loc[['b','d'],'age'] = [30,31]
df

         name  age  salary Education
a      swaraj   27   27000     btech
b      ujjwal   30   27000     btech
c    abhishek   26   30000       MCA
d         ram   31   10000     btech
e  rameshware   25   30000     btech

**Delete**

In [8]:
df["index"] = np.arange(0,len(df))
df

         name  age  salary Education  index
a      swaraj   27   27000     btech      0
b      ujjwal   30   27000     btech      1
c    abhishek   26   30000       MCA      2
d         ram   31   10000     btech      3
e  rameshware   25   30000     btech      4

In [9]:
df

         name  age  salary Education  index
a      swaraj   27   27000     btech      0
b      ujjwal   30   27000     btech      1
c    abhishek   26   30000       MCA      2
d         ram   31   10000     btech      3
e  rameshware   25   30000     btech      4

In [10]:
# delete the index column
df = df.drop(columns=["index"])
df

         name  age  salary Education
a      swaraj   27   27000     btech
b      ujjwal   30   27000     btech
c    abhishek   26   30000       MCA
d         ram   31   10000     btech
e  rameshware   25   30000     btech

In [11]:
df = df.drop(index=['e'])
df

       name  age  salary Education
a    swaraj   27   27000     btech
b    ujjwal   30   27000     btech
c  abhishek   26   30000       MCA
d       ram   31   10000     btech

**Change the order of the columns**

In [18]:
column = df.columns.to_list()
column

['name', 'age', 'salary', 'Education']

In [17]:
row = df.index.to_list()
row

['a', 'b', 'c', 'd']

In [19]:
df = df[['name', 'Education','age', 'salary']]
df

       name Education  age  salary
a    swaraj     btech   27   27000
b    ujjwal     btech   30   27000
c  abhishek       MCA   26   30000
d       ram     btech   31   10000

**set and reset the index**

In [46]:
df = pd.DataFrame({"name":['swaraj','ujjwal','abhishek','ram'],
                  "age":[27,28,26,29],
                  "salary":[27000,27000,30000,10000]},
                 index=['a','b','c','d'])
df

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

In [47]:
df = df.set_index('name')
df

          age  salary
name
swaraj     27   27000
ujjwal     28   27000
abhishek   26   30000
ram        29   10000

In [48]:
df.loc['swaraj']

age          27
salary    27000
Name: swaraj, dtype: int64

In [49]:
df = df.reset_index()

# Application

**extract first and last records**

In [50]:
df

       name  age  salary
0    swaraj   27   27000
1    ujjwal   28   27000
2  abhishek   26   30000
3       ram   29   10000

In [51]:
# top n records
df.head(2)

     name  age  salary
0  swaraj   27   27000
1  ujjwal   28   27000

In [52]:
# last n records
df.tail(2)

       name  age  salary
2  abhishek   26   30000
3       ram   29   10000

**Reaname the colums**

In [53]:
df = df.rename(columns={'age':'studant_age','salary':'student_salary'})
df

       name  studant_age  student_salary
0    swaraj           27           27000
1    ujjwal           28           27000
2  abhishek           26           30000
3       ram           29           10000

**sorting**

In [55]:
df.sort_values(by="studant_age")

       name  studant_age  student_salary
2  abhishek           26           30000
0    swaraj           27           27000
1    ujjwal           28           27000
3       ram           29           10000

In [56]:
df.sort_values(by="studant_age",ascending=False)

       name  studant_age  student_salary
3       ram           29           10000
1    ujjwal           28           27000
0    swaraj           27           27000
2  abhishek           26           30000

**To check all unique values**

In [57]:
df["student_salary"].unique()

array([27000, 30000, 10000])

In [59]:
df["student_salary"].nunique()

3

**to check each unique value and their corresponding count**

In [60]:
df["student_salary"].value_counts()

student_salary
27000    2
30000    1
10000    1
Name: count, dtype: int64

**Column data types**

In [62]:
df.dtypes

name                str
studant_age       int64
student_salary    int64
dtype: object

**Info about dataFrame**

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            4 non-null      str
 1   studant_age     4 non-null      int64
 2   student_salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

# Import the data from different sources

**to load excel file**

In [69]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [70]:
pd.read_excel(r"D:\AI_engineer_in_process\jupyter\data_import_test.xlsx")

        city  temperature
0  hyderabad           27
1     mumbai           30
2   banglore           24
3      delhi           32

In [72]:
pd.read_excel(r"D:\AI_engineer_in_process\jupyter\data_import_test.xlsx",sheet_name="Sheet2")

       city  humidity
0    mumbai        45
1  banglore        55
2     delhi        60
3   chennai        70
4   kolkata        50

In [73]:
pd.read_excel("data_import_test.xlsx")

        city  temperature
0  hyderabad           27
1     mumbai           30
2   banglore           24
3      delhi           32

In [75]:
pd.read_csv("data_import_test.csv")

        city  temperature
0  hyderabad           27
1     mumbai           30
2   banglore           24
3      delhi           32

In [87]:
t = pd.read_excel("flipkart_amazone_sales.xlsx")
t

,date,Flipkart Sales,Unnamed: 2,date.1,Amazone sales,Unnamed: 5,date.2,Flipkart Sales.1
0,2026-04-01,100,NaN,2026-04-01,300,NaN,2026-03-01,100
1,2026-04-02,200,NaN,2026-04-02,700,NaN,2026-03-02,200
2,2026-04-03,35,NaN,2026-04-03,55,NaN,2026-03-03,35
3,2026-04-04,44,NaN,2026-04-04,90,NaN,2026-03-04,44
4,2026-04-05,90,NaN,2026-04-05,200,NaN,2026-03-05,90

In [94]:
table1 = t[['date','Flipkart Sales']]
table1 = table1.rename(columns={"date":"Date",'Flipkart Sales':'Flipkart_Sales'})
table1

        Date  Flipkart_Sales
0 2026-04-01             100
1 2026-04-02             200
2 2026-04-03              35
3 2026-04-04              44
4 2026-04-05              90

In [95]:
table2 = t[["date.1","Amazone sales"]]
table2 = table2.rename(columns={"date.1":"Date","Amazone sales":"Amazone_sales"})
table2

        Date  Amazone_sales
0 2026-04-01            300
1 2026-04-02            700
2 2026-04-03             55
3 2026-04-04             90
4 2026-04-05            200

In [96]:
table3 = t[["date.2","Flipkart Sales.1"]]
table3 = table3.rename(columns={"date.2":"Date","Flipkart Sales.1":"Flipkart_Sales"})
table3

        Date  Flipkart_Sales
0 2026-03-01             100
1 2026-03-02             200
2 2026-03-03              35
3 2026-03-04              44
4 2026-03-05              90

# Table modification

**Combine**

- **Concat --> append :** in 2 tables, same column names with inteval values (different values)
- **Merge** --> join : in 2 tables, same column names with same values

**Concat**

- if 2 tables have same columns name and different values then we will use concat to combine them
- we can combine verticaly or horizontaly by defining the axis

In [97]:
pd.concat([table3,table1])

        Date  Flipkart_Sales
0 2026-03-01             100
1 2026-03-02             200
2 2026-03-03              35
3 2026-03-04              44
4 2026-03-05              90
0 2026-04-01             100
1 2026-04-02             200
2 2026-04-03              35
3 2026-04-04              44
4 2026-04-05              90

In [98]:
pd.concat([table1,table3],axis=1)

        Date  Flipkart_Sales       Date  Flipkart_Sales
0 2026-04-01             100 2026-03-01             100
1 2026-04-02             200 2026-03-02             200
2 2026-04-03              35 2026-03-03              35
3 2026-04-04              44 2026-03-04              44
4 2026-04-05              90 2026-03-05              90

In [99]:
pd.concat([table1,table3],axis=0)

        Date  Flipkart_Sales
0 2026-04-01             100
1 2026-04-02             200
2 2026-04-03              35
3 2026-04-04              44
4 2026-04-05              90
0 2026-03-01             100
1 2026-03-02             200
2 2026-03-03              35
3 2026-03-04              44
4 2026-03-05              90

In [101]:
pd.concat([table1,table3],axis=0,ignore_index=True)

        Date  Flipkart_Sales
0 2026-04-01             100
1 2026-04-02             200
2 2026-04-03              35
3 2026-04-04              44
4 2026-04-05              90
5 2026-03-01             100
6 2026-03-02             200
7 2026-03-03              35
8 2026-03-04              44
9 2026-03-05              90

**merge**

- if 2 tables have same columns names and also same values then we will use merge to combine them
- there are 4 type of joined set
- left joined - consider the left set values 
- right joined - consider the right set values
-

In [104]:
pd.merge(table1,table2,on="Date")

        Date  Flipkart_Sales  Amazone_sales
0 2026-04-01             100            300
1 2026-04-02             200            700
2 2026-04-03              35             55
3 2026-04-04              44             90
4 2026-04-05              90            200

In [108]:
table1 = pd.read_excel("data_import_test.xlsx",sheet_name="Sheet1")
table1

        city  temperature
0  hyderabad           27
1     mumbai           30
2   banglore           24
3      delhi           32

In [109]:
table2 = pd.read_excel("data_import_test.xlsx",sheet_name="Sheet2")
table2

       city  humidity
0    mumbai        45
1  banglore        55
2     delhi        60
3   chennai        70
4   kolkata        50

**Left joined**

In [110]:
pd.merge(table1,table2, on="city",how="left")

        city  temperature  humidity
0  hyderabad           27       NaN
1     mumbai           30      45.0
2   banglore           24      55.0
3      delhi           32      60.0

**right joined**

In [111]:
pd.merge(table1,table2, on="city",how="right")

       city  temperature  humidity
0    mumbai         30.0        45
1  banglore         24.0        55
2     delhi         32.0        60
3   chennai          NaN        70
4   kolkata          NaN        50

**inner joint**

In [112]:
pd.merge(table1,table2, on="city",how="inner")

       city  temperature  humidity
0    mumbai           30        45
1  banglore           24        55
2     delhi           32        60

**outer joint / full joint**

In [113]:
pd.merge(table1,table2, on="city",how="outer")

        city  temperature  humidity
0   banglore         24.0      55.0
1    chennai          NaN      70.0
2      delhi         32.0      60.0
3  hyderabad         27.0       NaN
4    kolkata          NaN      50.0
5     mumbai         30.0      45.0

In [118]:
# how to check common values are there or not 

set1 = set(table1["city"])
print(set1)
set2 = set(table2["city"])
print(set2)
set1.intersection(set2)

{'mumbai', 'hyderabad', 'banglore', 'delhi'}
{'delhi', 'banglore', 'mumbai', 'chennai', 'kolkata'}

{'banglore', 'delhi', 'mumbai'}

In [120]:
pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     ----- ---------------------------------- 1.6/11.9 MB 7.6 MB/s eta 0:00:02
     ------------ --------------------------- 3.7/11.9 MB 8.4 MB/s eta 0:00:01
     ----------------- ---------------------- 5.2/11.9 MB 8.4 MB/s eta 0:00:01
     --------------------- ------------------ 6.3/11.9 MB 7.4 MB/s eta 0:00:01
     ----------------------- ---------------- 6.8/11.9 MB 6.5 MB/s eta 0:00:01
     ------------------------- -------------- 7.6/11.9 MB 6.0 MB/s eta 0:00:01
     --------------------------- ------------ 8.1/11.9 MB 5.9 MB/s eta 0:00:01
     ----------------------------- ---------- 8.7/11.9 MB 5.4 MB/s eta 0:00:01
     ------------------------------ --------- 9.2/11.9 MB 5.0 MB/s eta 0:00:01
     -------------------------------- ------- 9.7/11.9 MB 4.6 MB/s eta 0:00:01
     ---------------------------------- ----- 10.2/11.9 MB 4.5 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 4.3 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 4.2 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 4.1 MB/s  0:00:03
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp311-cp311-win_amd64.whl size=248049 sha256=9b38101ac6b4691dcc0df4a07ae6f4ac4d7f8e30ad366cf450203e81e35b053f
  Stored in directory: c:\users\swaraj\appdata\local\pip\cache\wheels\17\cd\ed\2d49e9bac69cf09382e4c7cc20a2511202b48324b87db26019
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.