# Pandas (2D DataFrame)


- A pandas DataFrame is a 2 dimentional data structure, like a 2 dimentional array, or a table with row and columns.

**create a DataFrame**

- list of list
- 2D array
- Dict
- this above are the options by using we can create the DataFrame

In [8]:
import pandas as pd
import numpy as np

In [7]:
# 1) using list of list 

d = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['a','b','c'])
d

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [9]:
# 2) using 2D Array

a = np.array([[11,12,13],[14,15,16],[17,18,19]])
d = pd.DataFrame(a)
d

    0   1   2
0  11  12  13
1  14  15  16
2  17  18  19

In [11]:
# 3) using Dict

d = {"name":['swaraj','ujjwal','abhishek','ram'],'mobile No':[9421403501,1965487345,1234567890,10987654321],'email':['swaraj@gmail.com','ujjwal@gmail.com','abhishek@gmail.com','ram@gmail.com']}
df = pd.DataFrame(d)
df

       name    mobile No               email
0    swaraj   9421403501    swaraj@gmail.com
1    ujjwal   1965487345    ujjwal@gmail.com
2  abhishek   1234567890  abhishek@gmail.com
3       ram  10987654321       ram@gmail.com

In [12]:
df.shape

(4, 3)

In [13]:
df.ndim

2

# Extraction

In [14]:
df = pd.DataFrame({"name":['swaraj','ujjwal','abhishek','ram'],
                  "age":[27,28,26,29],
                  "salary":[27000,27000,30000,10000]},
                 index=['a','b','c','d'])
df

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

In [31]:
# extract 26
# 1) by using index
print(df.iloc[2, 1])

print ("=====================")
# by using index name
print(df.loc['c','age'])

26
=====================
26

In [27]:
# extract last two row

# 1) by index 
print(df.iloc[2:,:])

print("=============================")
#2) by index name
print (df.loc['c':'d',:])

       name  age  salary
c  abhishek   26   30000
d       ram   29   10000
=============================
       name  age  salary
c  abhishek   26   30000
d       ram   29   10000

In [37]:
# extract 2nd column

# 1) by using index

print(df.iloc[:,1])

print("=========================")

# 2) by using column name

print(df['age'])

a    27
b    28
c    26
d    29
Name: age, dtype: int64
=========================
a    27
b    28
c    26
d    29
Name: age, dtype: int64

In [38]:
# extract name and salary

df[['name','salary']]

       name  salary
a    swaraj   27000
b    ujjwal   27000
c  abhishek   30000
d       ram   10000

**By using Condition**

In [33]:
print(df)

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

In [35]:
# 1) age grater than 26

df[df['age'] > 26]

     name  age  salary
a  swaraj   27   27000
b  ujjwal   28   27000
d     ram   29   10000

In [41]:
# 2) extract salary equeal to 27000 and more
df[df['salary'] >= 27000]

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000

In [42]:
# 3 ) salary is 30000 and age should be 26

df[(df['salary'] == 30000) & (df['age'] == 26)]

       name  age  salary
c  abhishek   26   30000

In [44]:
# age between 26 to 28

# 1) by using condition

print(df [(df['age'] >= 26) & (df['age'] <= 28) ])

print("=================================================")

# 2) by using between operator

print (df [df['age'].between(26,28)])

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
=================================================
       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000

In [49]:
# salary of 10000, 27000, 30000

df[df['salary'].isin([10000,27000,30000])]

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000