# Pandas (2D DataFrame)


- A pandas DataFrame is a 2 dimentional data structure, like a 2 dimentional array, or a table with row and columns.

**create a DataFrame**

- list of list
- 2D array
- Dict
- this above are the options by using we can create the DataFrame

In [1]:
import pandas as pd
import numpy as np

In [7]:
# 1) using list of list 

d = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['a','b','c'])
d

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [9]:
# 2) using 2D Array

a = np.array([[11,12,13],[14,15,16],[17,18,19]])
d = pd.DataFrame(a)
d

    0   1   2
0  11  12  13
1  14  15  16
2  17  18  19

In [11]:
# 3) using Dict

d = {"name":['swaraj','ujjwal','abhishek','ram'],'mobile No':[9421403501,1965487345,1234567890,10987654321],'email':['swaraj@gmail.com','ujjwal@gmail.com','abhishek@gmail.com','ram@gmail.com']}
df = pd.DataFrame(d)
df

       name    mobile No               email
0    swaraj   9421403501    swaraj@gmail.com
1    ujjwal   1965487345    ujjwal@gmail.com
2  abhishek   1234567890  abhishek@gmail.com
3       ram  10987654321       ram@gmail.com

In [12]:
df.shape

(4, 3)

In [13]:
df.ndim

2

# Extraction

In [14]:
df = pd.DataFrame({"name":['swaraj','ujjwal','abhishek','ram'],
                  "age":[27,28,26,29],
                  "salary":[27000,27000,30000,10000]},
                 index=['a','b','c','d'])
df

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

In [31]:
# extract 26
# 1) by using index
print(df.iloc[2, 1])

print ("=====================")
# by using index name
print(df.loc['c','age'])

26
=====================
26

In [27]:
# extract last two row

# 1) by index 
print(df.iloc[2:,:])

print("=============================")
#2) by index name
print (df.loc['c':'d',:])

       name  age  salary
c  abhishek   26   30000
d       ram   29   10000
=============================
       name  age  salary
c  abhishek   26   30000
d       ram   29   10000

In [37]:
# extract 2nd column

# 1) by using index

print(df.iloc[:,1])

print("=========================")

# 2) by using column name

print(df['age'])

a    27
b    28
c    26
d    29
Name: age, dtype: int64
=========================
a    27
b    28
c    26
d    29
Name: age, dtype: int64

In [38]:
# extract name and salary

df[['name','salary']]

       name  salary
a    swaraj   27000
b    ujjwal   27000
c  abhishek   30000
d       ram   10000

**By using Condition**

In [33]:
print(df)

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

In [35]:
# 1) age grater than 26

df[df['age'] > 26]

     name  age  salary
a  swaraj   27   27000
b  ujjwal   28   27000
d     ram   29   10000

In [41]:
# 2) extract salary equeal to 27000 and more
df[df['salary'] >= 27000]

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000

In [42]:
# 3 ) salary is 30000 and age should be 26

df[(df['salary'] == 30000) & (df['age'] == 26)]

       name  age  salary
c  abhishek   26   30000

In [44]:
# age between 26 to 28

# 1) by using condition

print(df [(df['age'] >= 26) & (df['age'] <= 28) ])

print("=================================================")

# 2) by using between operator

print (df [df['age'].between(26,28)])

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
=================================================
       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000

In [49]:
# salary of 10000, 27000, 30000

df[df['salary'].isin([10000,27000,30000])]

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

# Modification

**1) Add**

In [2]:
df = pd.DataFrame({"name":['swaraj','ujjwal','abhishek','ram'],
                  "age":[27,28,26,29],
                  "salary":[27000,27000,30000,10000]},
                 index=['a','b','c','d'])
df

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

**Add single column**

In [3]:
df["Education"] = ['btech','btech','MCA','btech']
df

       name  age  salary Education
a    swaraj   27   27000     btech
b    ujjwal   28   27000     btech
c  abhishek   26   30000       MCA
d       ram   29   10000     btech

**Add single Row**

In [4]:
df.loc['e'] = ['rameshware',26,30000,'btech']

In [5]:
df

         name  age  salary Education
a      swaraj   27   27000     btech
b      ujjwal   28   27000     btech
c    abhishek   26   30000       MCA
d         ram   29   10000     btech
e  rameshware   26   30000     btech

**replace**

In [6]:
# replace rameshware age to 25

df.loc['e','age'] = 25
df

         name  age  salary Education
a      swaraj   27   27000     btech
b      ujjwal   28   27000     btech
c    abhishek   26   30000       MCA
d         ram   29   10000     btech
e  rameshware   25   30000     btech

In [7]:
df.loc[['b','d'],'age'] = [30,31]
df

         name  age  salary Education
a      swaraj   27   27000     btech
b      ujjwal   30   27000     btech
c    abhishek   26   30000       MCA
d         ram   31   10000     btech
e  rameshware   25   30000     btech

**Delete**

In [8]:
df["index"] = np.arange(0,len(df))
df

         name  age  salary Education  index
a      swaraj   27   27000     btech      0
b      ujjwal   30   27000     btech      1
c    abhishek   26   30000       MCA      2
d         ram   31   10000     btech      3
e  rameshware   25   30000     btech      4

In [9]:
df

         name  age  salary Education  index
a      swaraj   27   27000     btech      0
b      ujjwal   30   27000     btech      1
c    abhishek   26   30000       MCA      2
d         ram   31   10000     btech      3
e  rameshware   25   30000     btech      4

In [10]:
# delete the index column
df = df.drop(columns=["index"])
df

         name  age  salary Education
a      swaraj   27   27000     btech
b      ujjwal   30   27000     btech
c    abhishek   26   30000       MCA
d         ram   31   10000     btech
e  rameshware   25   30000     btech

In [11]:
df = df.drop(index=['e'])
df

       name  age  salary Education
a    swaraj   27   27000     btech
b    ujjwal   30   27000     btech
c  abhishek   26   30000       MCA
d       ram   31   10000     btech

**Change the order of the columns**

In [18]:
column = df.columns.to_list()
column

['name', 'age', 'salary', 'Education']

In [17]:
row = df.index.to_list()
row

['a', 'b', 'c', 'd']

In [19]:
df = df[['name', 'Education','age', 'salary']]
df

       name Education  age  salary
a    swaraj     btech   27   27000
b    ujjwal     btech   30   27000
c  abhishek       MCA   26   30000
d       ram     btech   31   10000

**set and reset the index**

In [46]:
df = pd.DataFrame({"name":['swaraj','ujjwal','abhishek','ram'],
                  "age":[27,28,26,29],
                  "salary":[27000,27000,30000,10000]},
                 index=['a','b','c','d'])
df

       name  age  salary
a    swaraj   27   27000
b    ujjwal   28   27000
c  abhishek   26   30000
d       ram   29   10000

In [47]:
df = df.set_index('name')
df

          age  salary
name
swaraj     27   27000
ujjwal     28   27000
abhishek   26   30000
ram        29   10000

In [48]:
df.loc['swaraj']

age          27
salary    27000
Name: swaraj, dtype: int64

In [49]:
df = df.reset_index()

# Application

**extract first and last records**

In [50]:
df

       name  age  salary
0    swaraj   27   27000
1    ujjwal   28   27000
2  abhishek   26   30000
3       ram   29   10000

In [51]:
# top n records
df.head(2)

     name  age  salary
0  swaraj   27   27000
1  ujjwal   28   27000

In [52]:
# last n records
df.tail(2)

       name  age  salary
2  abhishek   26   30000
3       ram   29   10000

**Reaname the colums**

In [53]:
df = df.rename(columns={'age':'studant_age','salary':'student_salary'})
df

       name  studant_age  student_salary
0    swaraj           27           27000
1    ujjwal           28           27000
2  abhishek           26           30000
3       ram           29           10000

**sorting**

In [55]:
df.sort_values(by="studant_age")

       name  studant_age  student_salary
2  abhishek           26           30000
0    swaraj           27           27000
1    ujjwal           28           27000
3       ram           29           10000

In [56]:
df.sort_values(by="studant_age",ascending=False)

       name  studant_age  student_salary
3       ram           29           10000
1    ujjwal           28           27000
0    swaraj           27           27000
2  abhishek           26           30000

**To check all unique values**

In [57]:
df["student_salary"].unique()

array([27000, 30000, 10000])

In [59]:
df["student_salary"].nunique()

3

**to check each unique value and their corresponding count**

In [60]:
df["student_salary"].value_counts()

student_salary
27000    2
30000    1
10000    1
Name: count, dtype: int64

**Column data types**

In [62]:
df.dtypes

name                str
studant_age       int64
student_salary    int64
dtype: object

**Info about dataFrame**

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            4 non-null      str
 1   studant_age     4 non-null      int64
 2   student_salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

# Import the data from different sources

**to load excel file**

In [69]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [70]:
pd.read_excel(r"D:\AI_engineer_in_process\jupyter\data_import_test.xlsx")

        city  temperature
0  hyderabad           27
1     mumbai           30
2   banglore           24
3      delhi           32

In [72]:
pd.read_excel(r"D:\AI_engineer_in_process\jupyter\data_import_test.xlsx",sheet_name="Sheet2")

       city  humidity
0    mumbai        45
1  banglore        55
2     delhi        60
3   chennai        70
4   kolkata        50

In [73]:
pd.read_excel("data_import_test.xlsx")

        city  temperature
0  hyderabad           27
1     mumbai           30
2   banglore           24
3      delhi           32

In [75]:
pd.read_csv("data_import_test.csv")

        city  temperature
0  hyderabad           27
1     mumbai           30
2   banglore           24
3      delhi           32

In [87]:
t = pd.read_excel("flipkart_amazone_sales.xlsx")
t

,date,Flipkart Sales,Unnamed: 2,date.1,Amazone sales,Unnamed: 5,date.2,Flipkart Sales.1
0,2026-04-01,100,NaN,2026-04-01,300,NaN,2026-03-01,100
1,2026-04-02,200,NaN,2026-04-02,700,NaN,2026-03-02,200
2,2026-04-03,35,NaN,2026-04-03,55,NaN,2026-03-03,35
3,2026-04-04,44,NaN,2026-04-04,90,NaN,2026-03-04,44
4,2026-04-05,90,NaN,2026-04-05,200,NaN,2026-03-05,90

In [94]:
table1 = t[['date','Flipkart Sales']]
table1 = table1.rename(columns={"date":"Date",'Flipkart Sales':'Flipkart_Sales'})
table1

        Date  Flipkart_Sales
0 2026-04-01             100
1 2026-04-02             200
2 2026-04-03              35
3 2026-04-04              44
4 2026-04-05              90

In [95]:
table2 = t[["date.1","Amazone sales"]]
table2 = table2.rename(columns={"date.1":"Date","Amazone sales":"Amazone_sales"})
table2

        Date  Amazone_sales
0 2026-04-01            300
1 2026-04-02            700
2 2026-04-03             55
3 2026-04-04             90
4 2026-04-05            200

In [96]:
table3 = t[["date.2","Flipkart Sales.1"]]
table3 = table3.rename(columns={"date.2":"Date","Flipkart Sales.1":"Flipkart_Sales"})
table3

        Date  Flipkart_Sales
0 2026-03-01             100
1 2026-03-02             200
2 2026-03-03              35
3 2026-03-04              44
4 2026-03-05              90

# Table modification

**Combine**

- **Concat --> append :** in 2 tables, same column names with inteval values (different values)
- **Merge** --> join : in 2 tables, same column names with same values

**Concat**

- if 2 tables have same columns name and different values then we will use concat to combine them
- we can combine verticaly or horizontaly by defining the axis

In [97]:
pd.concat([table3,table1])

        Date  Flipkart_Sales
0 2026-03-01             100
1 2026-03-02             200
2 2026-03-03              35
3 2026-03-04              44
4 2026-03-05              90
0 2026-04-01             100
1 2026-04-02             200
2 2026-04-03              35
3 2026-04-04              44
4 2026-04-05              90

In [98]:
pd.concat([table1,table3],axis=1)

        Date  Flipkart_Sales       Date  Flipkart_Sales
0 2026-04-01             100 2026-03-01             100
1 2026-04-02             200 2026-03-02             200
2 2026-04-03              35 2026-03-03              35
3 2026-04-04              44 2026-03-04              44
4 2026-04-05              90 2026-03-05              90

In [99]:
pd.concat([table1,table3],axis=0)

        Date  Flipkart_Sales
0 2026-04-01             100
1 2026-04-02             200
2 2026-04-03              35
3 2026-04-04              44
4 2026-04-05              90
0 2026-03-01             100
1 2026-03-02             200
2 2026-03-03              35
3 2026-03-04              44
4 2026-03-05              90

In [101]:
pd.concat([table1,table3],axis=0,ignore_index=True)

        Date  Flipkart_Sales
0 2026-04-01             100
1 2026-04-02             200
2 2026-04-03              35
3 2026-04-04              44
4 2026-04-05              90
5 2026-03-01             100
6 2026-03-02             200
7 2026-03-03              35
8 2026-03-04              44
9 2026-03-05              90

**merge**

- if 2 tables have same columns names and also same values then we will use merge to combine them
- there are 4 type of joined set
- left joined - consider the left set values 
- right joined - consider the right set values
-

In [104]:
pd.merge(table1,table2,on="Date")

        Date  Flipkart_Sales  Amazone_sales
0 2026-04-01             100            300
1 2026-04-02             200            700
2 2026-04-03              35             55
3 2026-04-04              44             90
4 2026-04-05              90            200

In [108]:
table1 = pd.read_excel("data_import_test.xlsx",sheet_name="Sheet1")
table1

        city  temperature
0  hyderabad           27
1     mumbai           30
2   banglore           24
3      delhi           32

In [109]:
table2 = pd.read_excel("data_import_test.xlsx",sheet_name="Sheet2")
table2

       city  humidity
0    mumbai        45
1  banglore        55
2     delhi        60
3   chennai        70
4   kolkata        50

**Left joined**

In [110]:
pd.merge(table1,table2, on="city",how="left")

        city  temperature  humidity
0  hyderabad           27       NaN
1     mumbai           30      45.0
2   banglore           24      55.0
3      delhi           32      60.0

**right joined**

In [111]:
pd.merge(table1,table2, on="city",how="right")

       city  temperature  humidity
0    mumbai         30.0        45
1  banglore         24.0        55
2     delhi         32.0        60
3   chennai          NaN        70
4   kolkata          NaN        50

**inner joint**

In [112]:
pd.merge(table1,table2, on="city",how="inner")

       city  temperature  humidity
0    mumbai           30        45
1  banglore           24        55
2     delhi           32        60

**outer joint / full joint**

In [113]:
pd.merge(table1,table2, on="city",how="outer")

        city  temperature  humidity
0   banglore         24.0      55.0
1    chennai          NaN      70.0
2      delhi         32.0      60.0
3  hyderabad         27.0       NaN
4    kolkata          NaN      50.0
5     mumbai         30.0      45.0

In [118]:
# how to check common values are there or not 

set1 = set(table1["city"])
print(set1)
set2 = set(table2["city"])
print(set2)
set1.intersection(set2)

{'mumbai', 'hyderabad', 'banglore', 'delhi'}
{'delhi', 'banglore', 'mumbai', 'chennai', 'kolkata'}

{'banglore', 'delhi', 'mumbai'}

# Working with database

**How to load the data from the mysql database**

In [2]:
# pip install PyMySQL

In [4]:
# import sqlalchemy
# import pandas as pd

**Connect mysql to python by using --> sqlalchemy.create_engine**

In [5]:
# db = sqlalchemy.create_engine('mysql+pymysql://root:1234@localhost:3306/rama')

**Querys of db**

In [6]:
#query = "SHOW TABLES"
#pd.read_sql_query(query,db)

In [7]:
# query = "SELECT * FROM actors"
# t = pd.read_sql_query(query,db)

**convert sql table to csv file**

In [8]:
# actors.to_csv("actores.csv")

# Data processing stapes


- Data exploration
- data cleaning
- data transformation

# Data exploration

- observing the internal data(values) of each column
- info()
- shape,
- columns,
- dtypes (observe the wrong data)
- unique values (observe the wrong data)
- no of unique values
- each category count
- duplicates
      - whether duplicates available or not
      - no of duplicates
      - exact duplicate records (observe)
- missing values
      - whether missing values available or not
      - no. of missing values
      - exact missing values records (observer)

In [2]:
cd = pd.read_csv("customer_data.csv")

In [3]:
cd

      customer_id  gender   age payment_method
0         C241288  Female  28.0    Credit Card
1         C111565    Male  21.0     Debit Card
2         C266599    Male  20.0           Cash
3         C988172  Female  66.0    Credit Card
4         C189076  Female  53.0           Cash
...           ...     ...   ...            ...
99452     C441542  Female  45.0    Credit Card
99453     C569580    Male  27.0           Cash
99454     C103292    Male  63.0     Debit Card
99455     C800631    Male  56.0           Cash
99456     C273973  Female  36.0    Credit Card

[99457 rows x 4 columns]

**Print all the rows from table**

In [5]:
# pd.set_option("display.max_rows",None)

In [6]:
cd.shape

(99457, 4)

In [7]:
cd.size

397828

In [8]:
cd.columns.to_list()

['customer_id', 'gender', 'age', 'payment_method']

In [10]:
cd.dtypes

customer_id           str
gender                str
age               float64
payment_method        str
dtype: object

In [12]:
cd.info()

<class 'pandas.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     99457 non-null  str
 1   gender          99457 non-null  str
 2   age             99338 non-null  float64
 3   payment_method  99457 non-null  str
dtypes: float64(1), str(3)
memory usage: 3.0 MB

In [14]:
cd['customer_id'].unique()

<StringArray>
['C241288', 'C111565', 'C266599', 'C988172', 'C189076', 'C657758', 'C151197',
 'C176086', 'C159642', 'C283361',
 ...
 'C288090', 'C231387', 'C953724', 'C226974', 'C513603', 'C441542', 'C569580',
 'C103292', 'C800631', 'C273973']
Length: 99457, dtype: str

In [15]:
cd['gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [16]:
cd['age'].unique()

array([28., 21., 20., 66., 53., 49., 32., 69., 60., 36., 29., 67., 25.,
       24., 65., 42., 46., 23., 27., 52., 44., 51., 50., 68., 43., 59.,
       54., 48., 40., 41., 19., 18., 22., 61., 45., 64., 33., 63., 34.,
       47., 38., 57., 30., 26., nan, 62., 39., 55., 56., 35., 31., 37.,
       58.])

In [19]:
cd['payment_method'].unique()

<StringArray>
['Credit Card', 'Debit Card', 'Cash']
Length: 3, dtype: str

In [20]:
cd['payment_method'].nunique()

3

In [22]:
cd['gender'].value_counts()

gender
Female    59482
Male      39975
Name: count, dtype: int64

**check if any wrong data is there**

In [25]:
l=[]
for i in cd['age'].unique().tolist():
    if type(i) not in [int,float]:
        l.append(i)
print(l)

[]

**Check Duplicate recodes**

In [34]:
cd.tail()

      customer_id  gender   age payment_method
99452     C441542  Female  45.0    Credit Card
99453     C569580    Male  27.0           Cash
99454     C103292    Male  63.0     Debit Card
99455     C800631    Male  56.0           Cash
99456     C273973  Female  36.0    Credit Card

In [41]:
cd.loc['99457'] = ['C273973','Female',36.0,'Credit Card']

In [42]:
cd.tail()

      customer_id  gender   age payment_method
99453     C569580    Male  27.0           Cash
99454     C103292    Male  63.0     Debit Card
99455     C800631    Male  56.0           Cash
99456     C273973  Female  36.0    Credit Card
99457     C273973  Female  36.0    Credit Card

In [45]:
cd.duplicated(['customer_id'])

0        False
1        False
2        False
3        False
4        False
         ...
99453    False
99454    False
99455    False
99456    False
99457     True
Length: 99458, dtype: bool

In [46]:
cd.duplicated(['customer_id']).sum()

np.int64(1)

In [43]:
cd[cd.duplicated(['customer_id'])].index.tolist()

['99457']

In [47]:
cd[cd.duplicated(['customer_id'])]

      customer_id  gender   age payment_method
99457     C273973  Female  36.0    Credit Card

In [49]:
cd.drop(index=['99457'])

      customer_id  gender   age payment_method
0         C241288  Female  28.0    Credit Card
1         C111565    Male  21.0     Debit Card
2         C266599    Male  20.0           Cash
3         C988172  Female  66.0    Credit Card
4         C189076  Female  53.0           Cash
...           ...     ...   ...            ...
99452     C441542  Female  45.0    Credit Card
99453     C569580    Male  27.0           Cash
99454     C103292    Male  63.0     Debit Card
99455     C800631    Male  56.0           Cash
99456     C273973  Female  36.0    Credit Card

[99457 rows x 4 columns]

**check for missing values**

In [9]:
cd.loc['99457']=['C273974','Female',np.nan,'Credit Card']
cd.loc['99458']=['C273975',np.nan,37.0,np.nan]

In [10]:
cd.tail()

      customer_id  gender   age payment_method
99454     C103292    Male  63.0     Debit Card
99455     C800631    Male  56.0           Cash
99456     C273973  Female  36.0    Credit Card
99457     C273974  Female   NaN    Credit Card
99458     C273975     NaN  37.0            NaN

In [11]:
cd.isnull()

       customer_id  gender    age  payment_method
0            False   False  False           False
1            False   False  False           False
2            False   False  False           False
3            False   False  False           False
4            False   False  False           False
...            ...     ...    ...             ...
99454        False   False  False           False
99455        False   False  False           False
99456        False   False  False           False
99457        False   False   True           False
99458        False    True  False            True

[99459 rows x 4 columns]

In [15]:
cd.isnull().sum()

customer_id         0
gender              1
age               120
payment_method      1
dtype: int64

In [40]:
l=[]
index = 0
for i in cd['age'].isnull():
    if i == True:
        l.append(index)
    index += 1
print(l)

[91, 92, 93, 94, 95, 97199, 97200, 97201, 97202, 97203, 97204, 97205, 97206, 97207, 97208, 97209, 97210, 97211, 97212, 97213, 97214, 97215, 97216, 97217, 97218, 97219, 97220, 97221, 97222, 97223, 97224, 97225, 97226, 97227, 97228, 97229, 97230, 97231, 97232, 97233, 97234, 97235, 97236, 97237, 97238, 97239, 97240, 97241, 97242, 97243, 97244, 97245, 97246, 97247, 97248, 97249, 97250, 97251, 97252, 97253, 97254, 97255, 97256, 97257, 97258, 97259, 97260, 97261, 97262, 97263, 97264, 97265, 97266, 97267, 97268, 97269, 97270, 97271, 97272, 97273, 97274, 97275, 97276, 97277, 97278, 97279, 97280, 97281, 97282, 97283, 97284, 97285, 97286, 97287, 97288, 97289, 97290, 97291, 97292, 97293, 97294, 97295, 97296, 97297, 97298, 97299, 97300, 97301, 97302, 97303, 97304, 97305, 97306, 97307, 97308, 97309, 97310, 97311, 97312, 99457]

In [35]:
len(l)

120

In [33]:
cd.iloc[97282]

customer_id       C118877
gender             Female
age                   NaN
payment_method       Cash
Name: 97282, dtype: object

In [60]:
# either gender or age is null print it

cd[(cd['gender'].isnull()) | (cd['age'].isnull())].index.tolist()

[91,
 92,
 93,
 94,
 95,
 97199,
 97200,
 97201,
 97202,
 97203,
 97204,
 97205,
 97206,
 97207,
 97208,
 97209,
 97210,
 97211,
 97212,
 97213,
 97214,
 97215,
 97216,
 97217,
 97218,
 97219,
 97220,
 97221,
 97222,
 97223,
 97224,
 97225,
 97226,
 97227,
 97228,
 97229,
 97230,
 97231,
 97232,
 97233,
 97234,
 97235,
 97236,
 97237,
 97238,
 97239,
 97240,
 97241,
 97242,
 97243,
 97244,
 97245,
 97246,
 97247,
 97248,
 97249,
 97250,
 97251,
 97252,
 97253,
 97254,
 97255,
 97256,
 97257,
 97258,
 97259,
 97260,
 97261,
 97262,
 97263,
 97264,
 97265,
 97266,
 97267,
 97268,
 97269,
 97270,
 97271,
 97272,
 97273,
 97274,
 97275,
 97276,
 97277,
 97278,
 97279,
 97280,
 97281,
 97282,
 97283,
 97284,
 97285,
 97286,
 97287,
 97288,
 97289,
 97290,
 97291,
 97292,
 97293,
 97294,
 97295,
 97296,
 97297,
 97298,
 97299,
 97300,
 97301,
 97302,
 97303,
 97304,
 97305,
 97306,
 97307,
 97308,
 97309,
 97310,
 97311,
 97312,
 '99457',
 '99458']

In [64]:
cd.isnull().sum(axis=1).tolist()

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [58]:
l2 = [] 
for i in cd.isnull().sum(axis=1).tolist():
    if i==2:
        l2.append(i)
print(l2)
len(l2)

[2]

1

**convert pandas.series to 1D array**

In [57]:
cd['customer_id'].to_numpy()

array(['C241288', 'C111565', 'C266599', ..., 'C800631', 'C273973',
       'C273973'], shape=(99458,), dtype=object)

**convert a 2D dataframe to 2D array**

In [58]:
cd[['customer_id','gender']].to_numpy()

array([['C241288', 'Female'],
       ['C111565', 'Male'],
       ['C266599', 'Male'],
       ...,
       ['C800631', 'Male'],
       ['C273973', 'Female'],
       ['C273973', 'Female']], shape=(99458, 2), dtype=object)

In [65]:
cd['age'].max()

np.float64(69.0)

In [66]:
cd['age'].min()

np.float64(18.0)

In [67]:
cd['age'].mean()

np.float64(43.42579450165594)

In [68]:
cd['age'].sum()

np.float64(4313875.0)

In [71]:
# extract the record where the age is maximum

cd[cd['age'] == cd['age'].max()]

      customer_id  gender   age payment_method
8         C159642    Male  69.0    Credit Card
77        C135790  Female  69.0           Cash
211       C171154  Female  69.0           Cash
212       C848969    Male  69.0           Cash
282       C336232    Male  69.0           Cash
...           ...     ...   ...            ...
98796     C203641  Female  69.0           Cash
98839     C685875    Male  69.0           Cash
99007     C955663  Female  69.0    Credit Card
99043     C274732  Female  69.0           Cash
99321     C321665    Male  69.0     Debit Card

[1897 rows x 4 columns]

In [72]:
cd["gender"].unique()

<StringArray>
['Female', 'Male', nan]
Length: 3, dtype: str

In [73]:
cd["gender"].nunique()

2

In [74]:
cd["gender"].value_counts()

gender
Female    59483
Male      39975
Name: count, dtype: int64

In [75]:
cd["gender"].mode()

0    Female
Name: gender, dtype: str

# Naming


- column name (excel) / variable name (statistics) / feature (ML & AI)
- Non- numeriacl = object (python)  / categorical (AI & ML) /qulitative data
- numariacal = numerical (python, AI and ML)/ quntitive data

In [5]:
sm = pd.DataFrame({'G':['M','F','M','F','M'],'marks':[50,60,70,80,90]})
sm

   G  marks
0  M     50
1  F     60
2  M     70
3  F     80
4  M     90

In [11]:
# avarage marks of male student

print("male Avg marks :",sm[sm['G'] == 'M']['marks'].mean())
print("female Avg marks :",sm[sm['G'] == 'F']['marks'].mean())

male Avg marks : 70.0
female Avg marks : 70.0

# groupby

In [13]:
sm.groupby("G")['marks'].mean()

G
F    70.0
M    70.0
Name: marks, dtype: float64

In [16]:
# avg age of female

cd[cd['gender']== 'Female']['age'].mean()

np.float64(43.45389820238336)

In [18]:
# avg age of each gender 
cd.groupby("gender")['age'].mean()

gender
Female    43.453898
Male      43.384136
Name: age, dtype: float64

# Crosstab

In [19]:
sm["E"] = ['Btech','Btech','Btech','MBA','MBA']
sm

   G  marks      E
0  M     50  Btech
1  F     60  Btech
2  M     70  Btech
3  F     80    MBA
4  M     90    MBA

In [23]:
pd.crosstab(sm['G'],sm['E'], margins=True)

E    Btech  MBA  All
G
F        1    1    2
M        2    1    3
All      3    2    5